### ISSUE TITLE
Thanks for destroying art

### ISSUE THREAD

**Issue by Naugustogi** [lllyasviel/Paints-UNDO#19]
Are we now going to fuck artists over even more?

If anything no piece of art can be trusted of not being ai generated anymore. And if you try to prove you've made it, well nope. This now allows to fake anything. Nobody will trust you anymore. This is fucked up beyond recognition.

You killed art, forever, you dont understand the craft, yet you try to mimick it.

I wish for justice. May your own creation destroy you.

**Comment by BlackHoleNo-23** [comment]
well, don't make it feel more proud

**Comment by tonyshen36** [comment]
shit artists are so pissed they can't sell shit art anymore lmao

**Comment by Naugustogi** [comment]
> shit artists are so pissed they can't sell shit art anymore lmao

You dont understand the problem. This society is build on trust. If you give your girlfriend an hardworked artpiece, or she gives you one, well good luck having trust issues.

If you cant express your thoughts anymore, then ai can overtake that too, individuality will be banned. 

At that point i dont want to delete any new technology, i want to delete the people working on it, not having any morality or thoughts over what they destroy. Not writing the ethical possibilitys, just putting something out without much writing how it works.

Like the atomic Bomb, not knowing what it can destroy, just putting it out without much thoughts. Considering that it could've ignites the atmosphere.

Now the real evil lies in building it in the first place.

**Comment by JapanYoshi** [comment]
> shit artists are so pissed they can't sell shit art anymore lmao

This repo's sole purpose is to let "shit artists" pass of their shit as actual art.

**Comment by barepixels** [comment]
let see your work and we will tell you if it's good or bad

**Comment by Naugustogi** [comment]
> Let see your work and we will tell you if it's good or bad. You talk as if you are some sort of "art god" without showing us anything

I dont care if you find it good or bad. I expressed things for myself, and if people say its fake they can fuck of. I enjoy showing it to others, i dont enjoy showing it to people who wants to train it.

May it be shit or not, whatever, my expression stays, my muscles worked on it.
Art is expression. It stayed this way for thousands of years.

**Comment by barepixels** [comment]
I was replying to [JapanYoshi](https://github.com/JapanYoshi)  

see the paragraph before my reply

**Comment by Naugustogi** [comment]
> I was replying to [JapanYoshi](https://github.com/JapanYoshi)
> 
> see the paragraph before my reply

I apologise, my mistake.

**Comment by barepixels** [comment]
What if one like one of the key frame better than the final image?  Should we let [JapanYoshi](https://github.com/JapanYoshi) rob us such opportunity?

**Comment by ruby109** [comment]
wow, so you can define art?

**Comment by protector131090** [comment]
> Are we now going to fuck artists over even more?
> 
> If anything no piece of art can be trusted of not being ai generated anymore. And if you try to prove you've made it, well nope. This now allows to fake anything. Nobody will trust you anymore. This is fucked up beyond recognition.
> 
> You killed art, forever, you dont understand the craft, yet you try to mimick it.
> 
> I wish for justice. May your own creation destroy you.

are you from Middle Ages? Photography destroyed art 50+ years ago. THan photoshop complitely destroyed art. art was dead for a long time.

**Comment by Naugustogi** [comment]
> > Are we now going to fuck artists over even more?
> > If anything no piece of art can be trusted of not being ai generated anymore. And if you try to prove you've made it, well nope. This now allows to fake anything. Nobody will trust you anymore. This is fucked up beyond recognition.
> > You killed art, forever, you dont understand the craft, yet you try to mimick it.
> > I wish for justice. May your own creation destroy you.
> 
> are you from Middle Ages? Photography destroyed art 50+ years ago. THan photoshop complitely destroyed art. art was dead for a long time.

Ah there are no people left holding a pen and draw paper? Computers are a different technology. I guess i have to use a stone and draw something on another stone. Wait thats a tool, so i have finger nails, i can simply scratch something into the ground, now happy?

**Comment by protector131090** [comment]
> > > Are we now going to fuck artists over even more?
> > > If anything no piece of art can be trusted of not being ai generated anymore. And if you try to prove you've made it, well nope. This now allows to fake anything. Nobody will trust you anymore. This is fucked up beyond recognition.
> > > You killed art, forever, you dont understand the craft, yet you try to mimick it.
> > > I wish for justice. May your own creation destroy you.
> > 
> > 
> > are you from Middle Ages? Photography destroyed art 50+ years ago. THan photoshop complitely destroyed art. art was dead for a long time.
> 
> Ah there are no people left holding a pen and draw on paper? Computers are a different technology. I guess i have to use a stone and draw something on another stone. Wait thats a tool, so i have finger nails, i can simply scratch something into the ground, now happy?

You just proved my point. There always will be people who want to draw no mater what tech we have. Ai is not exeption. Ai will never be a threat to real artist. Only to mediocre designers. With ai boom real art peaces will skydive in cost. Real artist will be celebrated like never before course they will be extremely rare.

**Comment by noorus** [comment]
> What if one like one of the key frame better than the final image? Should we let [JapanYoshi](https://github.com/JapanYoshi) rob us from such opportunity / tool?

If you drew the final image, surely you could go back to one of the "key frames" regardless?

**Comment by trentmkelly** [comment]
@Naugustogi 
You have LLM projects posted on Discord. Why is it destroying art, fucking over artists, the end of the world when it's image generation AI, but not destroying literature, fucking over writers, the end of the world when it's text generation AI?

**Comment by Naugustogi** [comment]
> @Naugustogi You have LLM projects posted on Github. Why is it destroying art, fucking over artists, the end of the world when it's image generation AI, but not destroying literature, fucking over writers, the end of the world when it's text generation AI?

I stoped posting my stable diffusion scripts either, because alot of gradio projects did it better and for text its abit more specialized with different architectures.

I have my own llms and own stuff trained on my own text. Nothing that could ever annoy anyone.

There is no difference except that i never open source my things i train on others work and just provide easy inference that anybody can program anyway. Its just a control thing which most people dont provide.

I dont fuck anybody over, they do.

**Comment by shenleqinau** [comment]
> 我们现在要把艺术家搞得更多吗？
> 
> 如果有的话，没有任何艺术品可以相信不再是人工智能生成的。如果你试图证明你已经成功了，那么不。这现在允许伪造任何东西。没有人会再信任你了。这简直面目全非。
> 
> 你扼杀了艺术，永远，你不了解这门手艺，但你试图模仿它。
> 
> 我希望伸张正义。愿你自己的创造摧毁你。



> 我们现在要把艺术家搞得更多吗？
> 
> 如果有的话，没有任何艺术品可以相信不再是人工智能生成的。如果你试图证明你已经成功了，那么不。这现在允许伪造任何东西。没有人会再信任你了。这简直面目全非。
> 
> 你扼杀了艺术，永远，你不了解这门手艺，但你试图模仿它。
> 
> 我希望伸张正义。愿你自己的创造摧毁你。

“It’s hilarious, if you can’t compete with skill, you’re destroying art. Anyway, you ‘artists’ are always right. If you’re not good, practice more. If you can’t handle losing, don’t play. It raises the overall watchability of creations, and it doesn’t affect artists with high painting skills at all.”

**Comment by PPAngel345** [comment]
> > 我们现在要把艺术家搞得更多吗？
> > 
> > 如果有的话，没有任何艺术品可以相信不再是人工智能生成的。如果你试图证明你已经成功了，那么不。这现在允许伪造任何东西。没有人会再信任你了。这简直面目全非。
> > 
> > 你扼杀了艺术，永远，你不了解这门手艺，但你试图模仿它。
> > 
> > 我希望伸张正义。愿你自己的创造摧毁你。
> 
> 
> 
> > 我们现在要把艺术家搞得更多吗？
> > 
> > 如果有的话，没有任何艺术品可以相信不再是人工智能生成的。如果你试图证明你已经成功了，那么不。这现在允许伪造任何东西。没有人会再信任你了。这简直面目全非。
> > 
> > 你扼杀了艺术，永远，你不了解这门手艺，但你试图模仿它。
> > 
> > 我希望伸张正义。愿你自己的创造摧毁你。
> 
> “It’s hilarious, if you can’t compete with skill, you’re destroying art. Anyway, you ‘artists’ are always right. If you’re not good, practice more. If you can’t handle losing, don’t play. It raises the overall watchability of creations, and it doesn’t affect artists with high painting skills at all.”

Art is something you, for instance, enjoy. Not *watch*, nobody says *watch art*, if you can't even handle basic English, how can you write a prompt? I might even be a better AI bro than you, so why even spending time following the damn project? It's useless.

**Comment by Seedmanc** [comment]
Artists started this war, no complains on losing it now. We just wanted to have fun with the new tech making us cute waifus, but they came in with hatred.

**Comment by barepixels** [comment]
> > What if one like one of the key frame better than the final image? Should we let [JapanYoshi](https://github.com/JapanYoshi) rob us from such opportunity / tool?
> 
> If you drew the final image, surely you could go back to one of the "key frames" regardless?

I don't think you will remember every step, hence the benefit of having history to refresh your memory

**Comment by noorus** [comment]
> > > What if one like one of the key frame better than the final image? Should we let [JapanYoshi](https://github.com/JapanYoshi) rob us from such opportunity / tool?
> > 
> > 
> > If you drew the final image, surely you could go back to one of the "key frames" regardless?
> 
> I don't think you will remember every step, hence the benefit of having history to refresh your memory and allowing you to do A B comparison
> 
> One of the key frame will not be exactly the same as one of your step since it is synthetic but you might like it better.
It is literally not history when it is synthesized nonsense, and this is not a function anyone needs for a legitimate purpose. This project's purpose is to fake process videos so that stolen and/or generated pictures can be sold as legitimate.

**Comment by Elvira626** [comment]
Naugustogi, don't worry. They can't fool everyone all the time. They can't destroy anything.

Genuine, skilled artists need to get back to the basics with pencil, paper, canvas, and paint. AI cannot fake that, and these tech bros who refuse to learn how to paint and draw cannot compete with someone who actually can paint. We have authenticity; they don't.

Pull the plug on electricity and they've got nothing. Their "creativity" is null. But even a digital-only artist can quickly adapt to traditional media. We have the real knowledge and skills. We can adapt. Furthermore, we don't "need" some stupid thing like this to scam and fool other people into thinking we actually drew something ourselves. 

They've gotten so audacious I just don't care anymore. They're absurd. We'll have to up our game, but ultimately, there's a limit to how much they can fake. They can't fake it ALL and they know it.

**Comment by xiaoleexiang** [comment]
> Naugustogi, don't worry. They can't fool everyone all the time. They can't destroy anything.
> 
> Genuine, skilled artists need to get back to the basics with pencil, paper, canvas, and paint. AI cannot fake that, and these tech bros who refuse to learn how to paint and draw cannot compete with someone who actually can paint. We have authenticity; they don't.
> 
> Pull the plug on electricity and they've got nothing. Their "creativity" is null. But even a digital-only artist can quickly adapt to traditional media. We have the real knowledge and skills. We can adapt. Furthermore, we don't "need" some stupid thing like this to scam and fool other people into thinking we actually drew something ourselves.
> 
> They've gotten so audacious I just don't care anymore. They're absurd. We'll have to up our game, but ultimately, there's a limit to how much they can fake. They can't fake it ALL and they know it.

https://interestingengineering.com/innovation/ai-powered-robot-can-reproduce-artists-paintings-at-scale
https://www.acrylicrobotics.ca/

![65a42e200f0d216cc92b0704_video1-poster-00001](https://github.com/lllyasviel/Paints-UNDO/assets/170864572/a9ea609f-aee3-4ec4-97e9-d6706c4fc4a0)

**Comment by Elvira626** [comment]
> This is last year, buddy:
> 
>     * https://interestingengineering.com/innovation/ai-powered-robot-can-reproduce-artists-paintings-at-scale
> 
>     * https://www.acrylicrobotics.ca/
> 
> 
> ![65a42e200f0d216cc92b0704_video1-poster-00001](https://private-user-images.githubusercontent.com/170864572/347614261-a9ea609f-aee3-4ec4-97e9-d6706c4fc4a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDk1MjEsIm5iZiI6MTcyMDY0OTIyMSwicGF0aCI6Ii8xNzA4NjQ1NzIvMzQ3NjE0MjYxLWE5ZWE2MDlmLWFlZTMtNGVjNC05N2U5LWQ2NzA2YzRmYzRhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQyMjA3MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzVhZDYyYTU3ZTJhZjYxZWU4ODAyNDNkMTNkODhlNTI0NDNjNzIyYTI4N2NiZjE4NGZiYTU0Y2E4MGNmNjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.afR6Wly7BQstcPgpfw0uuJ1sDs3ryAugep9xPqiEO5M)

Are you serious? You seriously think that the computer using one brush to "paint by numbers" is comparable to this? https://www.youtube.com/live/hL78FITGYdA?si=6QCzEl0XCaQ8522S or this? https://youtu.be/3K5FvNRCLkM?si=ATEwuvh2g7Hr9VAe https://www.youtube.com/watch?v=zD-cW8Ov9f8

Traditional media, especially oils, require a more subtle touch, many different brushes, many different brush strokes, brushwork and handling. Scrumbling, glazing, dry brush, palette knife, impasto, wipeaway, toning, wash, smearing, blending, yadda yadda. This stupid computer with one brush "filling in the blanks" line by line isn't even in the same _stratosphere_.

And besides that, I was talking about AI faking "work in progress" videos. You know, faking a video of a human being in front of a canvas, painting, mixing paints, etc. When do you propose that AI will be able to convincingly create a video of a person (who must look identical to the would-be scammer) "painting" in front of an easel, mixing paints, talking about their color mixtures, commenting on the adjustments they're making, real time? That's what these videos I linked to are showing. That's what genuine artists are capable of doing and are doing now. Can AI replicate this completely convincingly?

**Comment by xiaoleexiang** [comment]
@Elvira626 Oh, no! That's SO TRUE! They'll really never be able to reproduce the sweat on your forehead, or the stink emanating from your body, right? That's really impossible, for sure. They will never be able to do that. Wow. I guess you won then, right? It doesn't matter that the bot from a year ago could masterfully paint a masterpiece on a canvas if it can't... if it can't do something it's completely needless? LMAO

**Comment by Elvira626** [comment]
> @Elvira626 Oh, no! That's SO TRUE! They'll really never be able to reproduce the sweat on your forehead, or the stink emanating from your body, right? That's really impossible, for sure. They will never be able to do that. Wow. I guess you won then, right? It doesn't matter that the bot from a year ago could masterfully paint a masterpiece on a canvas if it can't... if it can't do something that is completely needless? LMAO

LOL, you are just butthurt because you proved yourself to be completely clueless and ignorant about what traditional art entails. You seriously thought that showing me this robot doing some basic "paint by numbers" was some sort of "gotcha"? Like, "oops, wow, they're already able to replace traditional artists!" lol! You _seriously_ thought that this painting robot's work is comparable to the majority of traditional art, and in particular traditional art painted in the style that tech bros most love to "emulate"? 

We're here talking about AI being able to fake WIPs and when I bring up that AI can't fake traditional art, you bring in your stupid paint-by-number robot? Ooooh, you got me with that one, lol.

**Comment by lllyasviel** [comment]
Hi all, as an action of [GitHub ToS]( https://docs.github.com/en/site-policy/acceptable-use-policies/github-bullying-and-harassment) we must lock this thread. 

For future comments please follow the instructions [here](https://github.com/lllyasviel/Paints-UNDO/issues/41).
