### ISSUE TITLE
What's the actual use-case scenario of this?

### ISSUE THREAD

**Issue by ZILtoid1991** [lllyasviel/Paints-UNDO#33]
It seems like the only usecase is scamming people for the sake of driving out artists from the industry.

However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.

Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.

**Comment by Amorano** [comment]
> It seems like the only usecase is scamming people for the sake of driving out artists from the industry.
> 
> However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.
> 
> Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.

Now do a pencil, copy machine or printing press.

Stop being Luddittes sitting behind your hundreds, if not thousands of dollars in tech, spouting junk about "this isnt art" or what it means to be an artist.

These are all tools -- use them, or dont. Stop attempting to bring some weird "logic" about who can decide what is a tool and isnt and what is art or isnt.

This is for actual issues -- not your personal or political ones.

**Comment by somespacecowboy** [comment]
> > It seems like the only usecase is scamming people for the sake of driving out artists from the industry.
> > However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.
> > Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.
> 
> Now do a pencil, copy machine or printing press.
> 
> Stop being Luddites sitting behind your hundreds, if not thousands of dollars in tech, spouting junk about "this is not art" or what it means to be an artist.
> 
> These are all tools -- use them, or do not. Stop attempting to bring some weird "logic" about who can decide what is a tool and is not and what is art or is not.
> 
> This is for actual issues -- not your personal or political ones.

Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - *this* tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.

**Comment by woct0rdho** [comment]
It's funny to see some art bros keep saying 'humans are creative', but can't think of a single use case of this project

The discussions were closed but I keep my words here

**Comment by somespacecowboy** [comment]
> It's funny to see some art bros keep saying 'humans are creative', but can't think of a single use case of this project
> 
> The discussions were closed but I keep my words here

Oh this again? I literally listed 4 use cases and then dismantled them in front of your eyes in the previous discussion, do you want me to spoonfeed you again like an infant?

**Comment by woct0rdho** [comment]
That means you didn't think of a use case that is not dismantled

**Comment by ARessegetesStery** [comment]
@woct0rdho 
Oh I come up with one.

Generate a random image, claim it as one's own work, and use this to synthesize the creation process. 
Then you can post it on websites! You become an "artist"! You get views and income! Beautiful as it is! 😆

**Comment by somespacecowboy** [comment]
> That means you didn't think of a use case that is not dismantled

I came up with more use cases than you and told you why they're not ethical or productive. Not to mention, you were stomped on pretty hard about your "production" point by about three people, because of course it's just laced in theft and laziness. I stand by the fact it's a little embarrassing your biggest brags are being uncreative, lazy, and unable to make any educated points without bragging about your meagre accomplishments. Most people code, have a degree, and can produce games, all without needing genai as their pacifiers. Get a grip.

**Comment by woct0rdho** [comment]
I don't argue if its use cases are legimate, productive, and valueable or not

I just use it, in production

**Comment by ARessegetesStery** [comment]
Of course you can use it illegitimately.

But legitimacy is the foundation of any discussion. If you decide to cross that, all I can do is wish you good luck. 

And your deeds will not be spotted.

**Comment by ZILtoid1991** [comment]
> Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - _this_ tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.

In fact, I use Neural Amp Modeler as my amp and pedal simulator for my electric guitar. I even was thinking about using some "hardwired" neural network in some game I've planned for the future.

**Comment by somespacecowboy** [comment]
> > Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - _this_ tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.
> 
> In fact, I use Neural Amp Modeler as my amp and pedal simulator for my electric guitar. I even was thinking about using some "hardwired" neural network in some game I've planned for the future.

See that's awesome - if I recall correctly some animation studios utilise AI toolsets for video processing and simplifying difficult elements such as hair, all of which works in tandem with human work. I don't think *anyone* is saying AI is inherently the problem - the issue begins when people who have no consideration for its harm and ethics make useless additions that don't add to the enjoyment of creation.

**Comment by Amorano** [comment]
> > > It seems like the only usecase is scamming people for the sake of driving out artists from the industry.
> > > However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.
> > > Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.
> > 
> > 
> > Now do a pencil, copy machine or printing press.
> > Stop being Luddites sitting behind your hundreds, if not thousands of dollars in tech, spouting junk about "this is not art" or what it means to be an artist.
> > These are all tools -- use them, or do not. Stop attempting to bring some weird "logic" about who can decide what is a tool and is not and what is art or is not.
> > This is for actual issues -- not your personal or political ones.
> 
> Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - _this_ tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.

lol. Sure thing, bud. 

Keep crying about not being able to spout 100% garbage that has nothing to do with the actual technical workings of the repository -- thinking that whatever you say, wherever you say it, needs to be addressed in the first place.

You are a bunch of sad "artists" who cant do much more than complain. All this time you could have shown everyone your "better" way instead of attempting to removing any usefulness to others you cant of which you cant seem to perceive the value.

That is a you problem.

**Comment by ARessegetesStery** [comment]
> Stop attempting to bring some weird "logic" about who can decide what is a tool and is not

@Amorano 
Say it to your legitimacy, of whether they are bringing some "weird logic", or what is actually "morality" and "intellectual property", in their discussion.

Well maybe that is a luxury for you who cannot give a complete argument without personal attack, resorting to your 20+ years of experience and laughing at others' tech, thinking that they do not deserve to discuss here in the first place 😆

**Comment by somespacecowboy** [comment]
> > > > It seems like the only usecase is scamming people for the sake of driving out artists from the industry.
> > > > However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.
> > > > Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.
> > > 
> > > 
> > > Now do a pencil, copy machine or printing press.
> > > Stop being Luddites sitting behind your hundreds, if not thousands of dollars in tech, spouting junk about "this is not art" or what it means to be an artist.
> > > These are all tools -- use them, or do not. Stop attempting to bring some weird "logic" about who can decide what is a tool and is not and what is art or is not.
> > > This is for actual issues -- not your personal or political ones.
> > 
> > 
> > Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - _this_ tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.
> 
> lol. Sure thing, bud.
> 
> Keep crying about not being able to spout 100% garbage that has nothing to do with the actual technical workings of the repository -- thinking that whatever you say, wherever you say it, needs to be addressed in the first place.
> 
> You are a bunch of sad "artists" who cant do much more than complain. All this time you could have shown everyone your "better" way instead of attempting to removing any usefulness to others you cant of which you cant seem to perceive the value.
> 
> That is a you problem.

Yap yap yap, you're going to put me to sleep having no actual reasoning and benefits to this, I'm getting a bit tuckered out hearing you guys stomp your little feet as if you're doing something profound. Ohhh I'm so talented writing little prompts into a textbox like a child, pfft. Do you also write your code using chatgpt?

**Comment by Amorano** [comment]
> > > > > It seems like the only usecase is scamming people for the sake of driving out artists from the industry.
> > > > > However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.
> > > > > Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.
> > > > 
> > > > 
> > > > Now do a pencil, copy machine or printing press.
> > > > Stop being Luddites sitting behind your hundreds, if not thousands of dollars in tech, spouting junk about "this is not art" or what it means to be an artist.
> > > > These are all tools -- use them, or do not. Stop attempting to bring some weird "logic" about who can decide what is a tool and is not and what is art or is not.
> > > > This is for actual issues -- not your personal or political ones.
> > > 
> > > 
> > > Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - _this_ tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.
> > 
> > 
> > lol. Sure thing, bud.
> > Keep crying about not being able to spout 100% garbage that has nothing to do with the actual technical workings of the repository -- thinking that whatever you say, wherever you say it, needs to be addressed in the first place.
> > You are a bunch of sad "artists" who cant do much more than complain. All this time you could have shown everyone your "better" way instead of attempting to removing any usefulness to others you cant of which you cant seem to perceive the value.
> > That is a you problem.
> 
> Yap yap yap, you're going to put me to sleep having no actual reasoning and benefits to this, I'm getting a bit tuckered out hearing you guys stomp your little feet as if you're doing something profound. Ohhh I'm so talented writing little prompts into a textbox like a child, pfft. Do you also write your code using chatgpt?

And what are you doing, loser?  Flapping your jaw about nothing.

Want actual change? Go do something to actually change it instead of attempting to play hero on nothing that matters.

or as you said, keep up your stupid, vapid yapyapyapyapyapyapyapyapyapyapyapyapyapyapyapyapyap

**Comment by somespacecowboy** [comment]
> > > > > > It seems like the only usecase is scamming people for the sake of driving out artists from the industry.
> > > > > > However, if I'm mistaken, then let me know. Maybe I'm just wrong, and this will be the tool that finally makes generative AI a real tool for creating art.
> > > > > > Also the supposed point of AI image generation was to **eliminate** the artists from the process of making art. If I really wanted to employ an idea guy to type their ideas into the prompt instead of me, then I already have one friend like that, who has dumb videogame ideas like "GTA, but set in Budapest, and has VR support", "hack some popular FPS to have VR support, then sell it to the original publisher", and other stuff like that.
> > > > > 
> > > > > 
> > > > > Now do a pencil, copy machine or printing press.
> > > > > Stop being Luddites sitting behind your hundreds, if not thousands of dollars in tech, spouting junk about "this is not art" or what it means to be an artist.
> > > > > These are all tools -- use them, or do not. Stop attempting to bring some weird "logic" about who can decide what is a tool and is not and what is art or is not.
> > > > > This is for actual issues -- not your personal or political ones.
> > > > 
> > > > 
> > > > Someone's getting a little emotional to opposing views! Luddites, seriously? Most of the people speaking out about this here are also in tech and probably have used AI in one way or another - _this_ tool is pretty valid to question. Not to mention, the constant deletion of discussions here shows that there's validity in questioning why there are people who disagree with you. I think you've built an echo chamber around yourself buddy.
> > > 
> > > 
> > > lol. Sure thing, bud.
> > > Keep crying about not being able to spout 100% garbage that has nothing to do with the actual technical workings of the repository -- thinking that whatever you say, wherever you say it, needs to be addressed in the first place.
> > > You are a bunch of sad "artists" who cant do much more than complain. All this time you could have shown everyone your "better" way instead of attempting to removing any usefulness to others you cant of which you cant seem to perceive the value.
> > > That is a you problem.
> > 
> > 
> > Yap yap yap, you're going to put me to sleep having no actual reasoning and benefits to this, I'm getting a bit tuckered out hearing you guys stomp your little feet as if you're doing something profound. Ohhh I'm so talented writing little prompts into a textbox like a child, pfft. Do you also write your code using chatgpt?
> 
> And what are you doing, loser? Flapping your jaw about nothing.
> 
> Want actual change? Go do something to actually change it instead of attempting to play hero on nothing that matters.
> 
> or as you said, keep up your stupid, vapid yapyapyapyapyapyapyapyapyapyapyapyapyapyapyapyapyap
> 
> I have been an artist at studios for over 20 years. You are a jerk off posting vapid junk.
> 
> Prompt that.

Pfft 20 years and you really don't show much maturity flaring up over other people's opinions, it's just funny! Also you can't exactly call me out on that behaviour when you're doing the same, can you? You don't know my life or what I have contributed but when it comes to making valid points you just resort to bragging. I also just don't get why as an artist you'd self sabotage yourself, but you do you if you want you work to be replaced by lazy bastards, I guess? Have fun? Again, a little embarrassing, especially if you're an adult with this much experience.

**Comment by Amorano** [comment]
> You don't know my life or what I have contributed but when it comes to making valid points you just resort to bragging. I also just don't get why as an artist you'd self sabotage yourself, but you do you if you want you work to be replaced by lazy bastards, I guess? Have fun? Again, a little embarrassing, especially if you're an adult with this much experience.

Who cares? cry harder.

Do something other than whatever you think you are not accomplishing here.

You are not proud of your life and accomplishments, sounds like you have more than a single personal issue you should resolve before attempting to tell other's how they should exist and what value things are worth, according you.

**Comment by somespacecowboy** [comment]
> You are not proud of your life and accomplishments, sounds like you have more than a single personal issue you should resolve before attempting to tell other's how they should exist and what value things are worth, according you.

See this is why you AI bros make no sense to me - I've never once made any brash assumptions over you besides the conversations we've had here, yet you're pouncing on me making baseless claims about my securities and immediately defending the usage of this tool with what? No solid and ethical usages, just your work and experience as if it makes you an expert.

I can tell you one thing, because it's already happening, that *this* has not been used with the artist in mind, and will never most likely - every single defender of this tool has simply resorted to insults and doomposting as if they're in a game lobby. People are upset because their hard work is being robbed, their livelihoods are being tested - just because *you* managed to get into the industry 20 years ago, doesn't mean things are the same. People aren't upset because lack of skill or because it's AI, you are simply glossing over every single thing people are saying under the pretence you know better because you haven't suffered the fact that people have to *try* to protect their work because people are taking it without permission. Worse, they're now using tools to make false proof that they made this work.

This is probably my last contribution to this conversation, don't think that you've made some point if I ignore you. I know that you won't listen and will still resort to stamping your feet and insulting my character - which you don't have the right to do, by the way. But then again, you don't have the right to use people's data to fake your talent, but you do anyways. Oh well.

**Comment by Amorano** [comment]
>
> See this is why you AI bros make no sense to me - I've never once made any brash assumptions over you besides the conversations we've had here, yet you're pouncing on me making baseless claims about my securities and immediately defending the usage of this tool with what? No solid and ethical usages, just your work and experience as if it makes you an expert.
> 

NO ONE NEEDS TO JUSTIFY TO YOU WHY A TOOL EXISTS.

MOVE ON.

**Comment by lllyasviel** [comment]
Hi all, as an action of [GitHub ToS]( https://docs.github.com/en/site-policy/acceptable-use-policies/github-bullying-and-harassment) we must lock this thread. 

For future comments please follow the instructions [here](https://github.com/lllyasviel/Paints-UNDO/issues/41).
