### ISSUE TITLE
Why would you pretend this is not AIGC if you are proud of AIGC?

### ISSUE THREAD

**Issue by xyyy9** [lllyasviel/Paints-UNDO#34]
It's unacceptable and irresponsible to develop and distribute tools that are designed to deceive. Such technology not only undermines the trust in digital content but also disrespects genuine artists and their skills. I urge you to reconsider the ethical implications of your project. 

I demand an explanation: Why would you choose to hide that this is AIGC if you truly believe in the technology’s merits?

**Comment by Elvira626** [comment]
Because apparently there is a demand among some circles to deceive. That's pretty much obvious, isn't it?

**Comment by AndreiSva** [comment]
This is a pretty cool project that could potentially be built-upon to improve text to image AI.

**Comment by woct0rdho** [comment]
Who is pretending? What is pretended?

Timelapses can be generated by AIGC. Isn't it obvious?

**Comment by lllyasviel** [comment]
Hi all, as an action of [GitHub ToS]( https://docs.github.com/en/site-policy/acceptable-use-policies/github-bullying-and-harassment) we must lock this thread. 

For future comments please follow the instructions [here](https://github.com/lllyasviel/Paints-UNDO/issues/41).
