### ISSUE TITLE
Can't start the UI. Error message

### ISSUE THREAD

**Issue by eizoxx** [lllyasviel/Paints-UNDO#52]
Hello all, for some reason, I can't use the user interface because when I enter this command: "python gradio_app.py" in the command line, I get this error message:

Traceback (most recent call last):
  File "E:\AI\Paints-UNDO\gradio_app.py", line 15, in <module>
    import memory_management
  File "E:\AI\Paints-UNDO\memory_management.py", line 9, in <module>
    torch.zeros((1, 1)).to(gpu, torch.float32)
  File "C:\Users\user\.conda\envs\paints_undo\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Does anyone know how to fix this problem?

My GPU is powerful enough to run this thing...

![image](https://github.com/lllyasviel/Paints-UNDO/assets/46431906/301f89fb-3050-4a5a-9d1f-a01e51945a2d)

**Comment by RaiderUser** [comment]
see #6

**Comment by eizoxx** [comment]
This thread solved it:
https://github.com/lllyasviel/Paints-UNDO/issues/6
