### ISSUE TITLE
I think Mr. Zhang might have had some personal issues with Artists?

### ISSUE THREAD

**Issue by ED-Y-S** [lllyasviel/Paints-UNDO#69]
I cannot imagine that some proper "researchers" would devote this vast amount of time to devising a model solely to deceive and create a fake process of humans creating artwork with no other plausible benefits.

Respectfully, are you okay?

**Comment by V3ntus** [comment]
@ED-Y-S it is very much worth it. Evaluate your own values, you sound like you live a sad life.

**Comment by ninjasaid2k** [comment]
> I cannot imagine that some proper "researchers" would devote this vast amount of time to devising a model solely to deceive and create a fake process of humans creating artwork with no other plausible benefits.
> 
> Respectfully, are you okay?

Please stop spamming the issue section of the repository. This is not meant to be a soapbox, this is meant for technical issues only. If you have personal problem with the project do not air it here, you will not convince anyone in such a manner.

**Comment by AlizerUncaged** [comment]
@ED-Y-S take Ls, stay mad until you break

**Comment by ED-Y-S** [comment]
> @ED-Y-S take Ls, stay mad until you break

L.... as in? I apologize that I respect artists' works and have no intention to fake it...?

**Comment by ED-Y-S** [comment]
> @ED-Y-S it is very much worth it. Evaluate your own values, you sound like you live a sad life.

Worth what? You can finally thoroughly fake that you made the art?

What sad life? A life of no deception? Sounds great to me!

**Comment by V3ntus** [comment]
@ED-Y-S The only deception here is your ignorance. Maybe you should make informed and educated decisions into your claims instead of following the sheep.

**Comment by ED-Y-S** [comment]
> @ED-Y-S The only deception here is your ignorance. Maybe you should make informed and educated decisions into your claims instead of following the sheep.

You are replying with nothing burger.

What sheep? Your AI bubble which is the just filled with transformer-to-transformer LLM spamming, with intention of pivoting towards Neural Network cuz it’s too “difficult to profit on?” Come the f on.

**Comment by V3ntus** [comment]
Nothing burger lol learn English

**Comment by ED-Y-S** [comment]
> Nothing burger lol learn English

nothing burger
“something that is or turns out to be or lacking in substance.”

You are once again spewing *nothing burger* now with newly added ad hominem because you have no idea of what have just said….
