### ISSUE TITLE
Are they idiots? This is evil

### ISSUE THREAD

**Issue by ghost** [lllyasviel/Paints-UNDO#7]
Really the assholes programmers want to disguise this as a way to support artists when it will simply be used to counterfeit art, they try to absolve themselves of all blame by saying that it is not their responsibility for how people use this shitty tool that was created specifically to counterfeit

I do blame you and I hope people do too

**Comment by Amorano** [comment]
so, if that is your biggest gripe, go yell at the pencil maker, moron. They also made a tool that anyone can use to copy anyone else.

Your argument is empty and vapid. And before you attempt to be an additional clown, I have been doing physical and VFX for 20+ years in Film and VFX, building the literal pipelines used at Nick and Disney.

Buy a mitt, catch a clue -- you are not the definer of what tools are useful nor what "artist" means. Crawl back to your cave and stay mad.

**Comment by Dazuny** [comment]
> Así que, si esa es tu mayor queja, ve a gritarle al fabricante de lápices, idiota. También crearon una herramienta que cualquiera puede usar para copiar a cualquier otra persona.
> 
> Tu argumento es vacío y superficial. Y antes de que intentes hacerte el payaso más, te diré que llevo más de 20 años haciendo arte físico y efectos visuales digitales en cine y televisión, construyendo los canales literales que se utilizan en Nickelodeon y Disney.
> 
> Compra un guante, capta la idea: no eres tú quien define qué herramientas son útiles ni qué significa "artista". Vuelve a tu cueva y sigue enfadado.

What a stupid comparison you made, Don't want to come here with a fallacy of authority, I don't care who you are, that won't change the fact that this will be used to steal and forge, in the future I'm sure we'll see, you guys just play the idiot.

**Comment by Amorano** [comment]
> > Así que, si esa es tu mayor queja, ve a gritarle al fabricante de lápices, idiota. También crearon una herramienta que cualquiera puede usar para copiar a cualquier otra persona.
> > Tu argumento es vacío y superficial. Y antes de que intentes hacerte el payaso más, te diré que llevo más de 20 años haciendo arte físico y efectos visuales digitales en cine y televisión, construyendo los canales literales que se utilizan en Nickelodeon y Disney.
> > Compra un guante, capta la idea: no eres tú quien define qué herramientas son útiles ni qué significa "artista". Vuelve a tu cueva y sigue enfadado.
> 
> What a stupid comparison you made, Don't want to come here with a fallacy of authority, I don't care who you are, that won't change the fact that this will be used to steal and forge, in the future I'm sure we'll see, you guys just play the idiot.

Jerk off, you literally are posting around here what artist means.

LOOK IN THE MIRROR.

**Comment by Dazuny** [comment]
> > > Así que, si esa es tu mayor queja, ve a gritarle al fabricante de lápices, idiota. También crearon una herramienta que cualquiera puede usar para copiar a cualquier otra persona.
> > > Tu argumento es vacío y superficial. Y antes de que intentes hacerte el payaso más, te diré que llevo más de 20 años haciendo arte físico y efectos visuales digitales en cine y televisión, construyendo los canales literales que se utilizan en Nickelodeon y Disney.
> > > Compra un guante, capta la idea: no eres tú quien define qué herramientas son útiles ni qué significa "artista". Vuelve a tu cueva y sigue enfadado.
> > 
> > 
> > What a stupid comparison you made, Don't want to come here with a fallacy of authority, I don't care who you are, that won't change the fact that this will be used to steal and forge, in the future I'm sure we'll see, you guys just play the idiot.
> 
> Jerk off, you literally are posting around here what artist means.
> 
> LOOK IN THE MIRROR.

You really show me that you have terrible reading comprehension and that your intelligence is quite questionable with your previous comparison, I am not going to argue with someone so stupid.

**Comment by Amorano** [comment]
> > > > Así que, si esa es tu mayor queja, ve a gritarle al fabricante de lápices, idiota. También crearon una herramienta que cualquiera puede usar para copiar a cualquier otra persona.
> > > > Tu argumento es vacío y superficial. Y antes de que intentes hacerte el payaso más, te diré que llevo más de 20 años haciendo arte físico y efectos visuales digitales en cine y televisión, construyendo los canales literales que se utilizan en Nickelodeon y Disney.
> > > > Compra un guante, capta la idea: no eres tú quien define qué herramientas son útiles ni qué significa "artista". Vuelve a tu cueva y sigue enfadado.
> > > 
> > > 
> > > What a stupid comparison you made, Don't want to come here with a fallacy of authority, I don't care who you are, that won't change the fact that this will be used to steal and forge, in the future I'm sure we'll see, you guys just play the idiot.
> > 
> > 
> > Jerk off, you literally are posting around here what artist means.
> > LOOK IN THE MIRROR.
> 
> You really show me that you have terrible reading comprehension and that your intelligence is quite questionable with your previous comparison, I am not going to argue with someone so stupid.

![image](https://github.com/lllyasviel/Paints-UNDO/assets/225178/befb8551-147f-4665-bb52-4e824625de3b)


That you, stupid?

You think we cant read what you wrote?
![image](https://github.com/lllyasviel/Paints-UNDO/assets/225178/58dc944c-955f-4ae0-9b1e-eadbeeb66ac6)

```
un verdadero artista profesional no necesita esta herramienta inútil y estúpida que solo fue hecha para plagiar y falsificar.
```

Says who? You? sure thing, chief. Talk about a false sense of authoirty. Get bent.

**Comment by Dazuny** [comment]
> > > > > Así que, si esa es tu mayor queja, ve a gritarle al fabricante de lápices, idiota. También crearon una herramienta que cualquiera puede usar para copiar a cualquier otra persona. 
> > > > > Tu argumento es vacío y superficial. Y antes de que intentes hacerte el payaso más, te diré que llevará más de 20 años haciendo arte físico y efectos visuales digitales en cine y televisión, construyendo los canales literales que se utilizan en Nickelodeon y Disney. 
> > > > > Compra unos guantes, capta la idea: no eres tú quien define qué herramientas son útiles ni qué significa "artista". Vuelve a tu cueva y sigue enfadado.
> > > > 
> > > > 
> > > > Qué comparación más estúpida hiciste, no quiero venir aquí con una falacia de autoridad, no me importa quién seas, eso no cambiará el hecho de que esto se usará para robar y falsificar, en el futuro estoy seguro que lo veremos, ustedes solo se hacen los idiotas.
> > > 
> > > 
> > > ¡Pajeate! Literalmente estás publicando por aquí lo que significa ser artista. 
> > > MÍRATE AL ESPEJO.
> > 
> > 
> > Realmente me demuestras que tienes una pésima comprensión lectora y que tu inteligencia es bastante cuestionable con tu comparación anterior, no voy a discutir con alguien tan estúpido.
> 
> ![imagen](https://private-user-images.githubusercontent.com/225178/347068815-befb8551-147f-4665-bb52-4e824625de3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDkyNTEsIm5iZiI6MTcyMDU0ODk1MSwicGF0aCI6Ii8yMjUxNzgvMzQ3MDY4ODE1LWJlZmI4NTUxLTE0N2YtNDY2NS1iYjUyLTRlODI0NjI1ZGUzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxODE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzZhNDE0YTViYTY1N2Q3YjBmNDM3ZGNkMDE2ZDNlOTIwMWIyZGU2NzljZGNmN2Q0ZTVlOTI2YWFjYjc3ZGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NywciIbmy3gzfC3AR54rzyD3lCYnMQSAsXOi1Vg0aYk)
> 
> ¿Eres tú, tonto?
> 
> ¿Crees que no podemos leer lo que escribiste? ![imagen](https://private-user-images.githubusercontent.com/225178/347068871-58dc944c-955f-4ae0-9b1e-eadbeeb66ac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NDkyNTEsIm5iZiI6MTcyMDU0ODk1MSwicGF0aCI6Ii8yMjUxNzgvMzQ3MDY4ODcxLTU4ZGM5NDRjLTk1NWYtNGFlMC05YjFlLWVhZGJlZWI2NmFjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxODE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODE5ZmMyZWM5NzUwYjdjNWQ0MTVmYTM2NDAzZGM0NGNiMWI1MGIxYTY4NGI0OWFlYjI3ZDU2OTAwNjU4YzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a6fgccOFBPsVxFm8YWIGWvrq3mYjaQi3E0SsC6y5OVE)
> 
> ```
> un verdadero artista profesional no necesita esta herramienta inútil y estúpida que solo fue hecha para plagiar y falsificar.
> ```
> 
> ¿Quién lo dice? ¿Tu? Claro que sí, jefe. ¡Qué falsa sensación de autoridad! ¡Que se joda!

I won't keep wasting my time with the "Disney worker" HAHAHAHA 🤫

**Comment by Amorano** [comment]
this is you saying 3 posts ago you were not going to argue.

This is how stupid and uncommitted you are to your own message. congrats.

**Comment by Dazuny** [comment]
> Esto es lo que dijiste hace 3 publicaciones antes: no ibas a discutir.
> 
> Así de estúpido y poco comprometido eres con tu propio mensaje. Felicidades.

I'm not arguing, I'm making fun of your stupidity zzzzzz

**Comment by Amorano** [comment]
Sure thing... stay committed to not bringing yourself down to my level -- gets better with each reply.

**Comment by davizca** [comment]
> > > > > Así que, si esa es tu mayor queja, ve a gritarle al fabricante de lápices, idiota. También crearon una herramienta que cualquiera puede usar para copiar a cualquier otra persona.
> > > > > Tu argumento es vacío y superficial. Y antes de que intentes hacerte el payaso más, te diré que llevo más de 20 años haciendo arte físico y efectos visuales digitales en cine y televisión, construyendo los canales literales que se utilizan en Nickelodeon y Disney.
> > > > > Compra un guante, capta la idea: no eres tú quien define qué herramientas son útiles ni qué significa "artista". Vuelve a tu cueva y sigue enfadado.
> > > > 
> > > > 
> > > > What a stupid comparison you made, Don't want to come here with a fallacy of authority, I don't care who you are, that won't change the fact that this will be used to steal and forge, in the future I'm sure we'll see, you guys just play the idiot.
> > > 
> > > 
> > > Jerk off, you literally are posting around here what artist means.
> > > LOOK IN THE MIRROR.
> > 
> > 
> > You really show me that you have terrible reading comprehension and that your intelligence is quite questionable with your previous comparison, I am not going to argue with someone so stupid.
> 
> ![image](https://private-user-images.githubusercontent.com/225178/347068815-befb8551-147f-4665-bb52-4e824625de3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTA0MjAsIm5iZiI6MTcyMDU1MDEyMCwicGF0aCI6Ii8yMjUxNzgvMzQ3MDY4ODE1LWJlZmI4NTUxLTE0N2YtNDY2NS1iYjUyLTRlODI0NjI1ZGUzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxODM1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODE3NzFlMjg4NjU0NmQ0MmVhZTg4MGMyMjlmZTgyMzA2MGZkYWVmY2E0ZGUzZWZlZDg3NDAzYzNiZjNmMTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MwAC4l9EODmiakFcQ9FoXORVtQ8kOMpMqsdfKYb0MQk)
> 
> That you, stupid?
> 
> You think we cant read what you wrote?
> 
> ```
> un verdadero artista profesional no necesita esta herramienta inútil y estúpida que solo fue hecha para plagiar y falsificar.
> ```
> 
> Says who? You? sure thing, chief. Talk about a false sense of authoirty. Get bent.

Don't waste your time. The best we can do is to just let then keep talking and punching the sea. I shouldn't answered him but sometimes these guys are stubborn as hell. Peace!

**Comment by Amorano** [comment]
Oh hey, look at that, account deleted. =D

**Comment by ZeroCool22** [comment]
![d73b5b3fdaed24e847ccd678c2c2c9f1](https://github.com/lllyasviel/Paints-UNDO/assets/13344308/637816c8-10b5-41be-b93d-9744c36fdd30)

**Comment by yacineMTB** [comment]
posting in ebin thread

**Comment by JapanYoshi** [comment]
Once again the AI Bros™ can’t justify the existence of a tool created by plagiarizing myriads of artists (yes, real artists that create art by themselves), whose only legitimate, non-contrived intent is generating forgery.

**Comment by AndreiSva** [comment]
You have to draw a line somewhere between what you consider "learning" off of material (eg: transformative) and what you consider copyright infringement.

Obviously today's ML is not similar to human learning in any meaningful way, but it could probably be considered learning under a lot of meanings of the word. I think it would be a inconsistent to allow humans to learn off of copyrighted material and not allow computers.

Under some circumstances we do not in fact allow people with extensive knowledge of copyrighted codebases to write code for open source projects (see WINE developers), but I think this would not apply for a correctly trained model.

I think correctly trained models should be considered transformative, especially this model, which can't reproduce copyrighted artworks.

**Comment by JapanYoshi** [comment]
> Obviously today's ML is not similar to human learning in any meaningful way,

Say no more, fam. It's copyright infringement for the intent to defraud people by forging AI hallucinations as real art.

**Comment by Kotori05** [comment]
Someone is using foul language under technical questions.
But I cannot say that these words are demons. Because demons are people who use foul language.

There is no doubt that this technology has brought image artificial intelligence one step closer to "becoming human". Now it is a reverse deduction, and in the future it may be possible for AI to learn the human painting process. Rather than eliminating Gaussian noise.

Someone has lost his mind. If he has so much energy to use foul language to technicians, why doesn't he resist those real scammers? This sounds like the Inquisition broke into the Wright brothers' house and said to them: "You know, flying is something controlled by God... How can you let humans fly? I can't imagine what people would do if they flew into the sky! Wright brothers, you are really demons!"

Such people have existed for a long time.
In the 19th century, spinning machines and cameras were called "demons" by them;
In the 20th century, electronic typesetting was called "demon" by them;
Now it is AI.

Why do they still dare to use github? This is a cloud platform that integrates complex science and technology. It's too dangerous! They can't imagine what these programmers dare to do! Why don't they just degenerate into slugs and find a wet crack in the rocks to crawl into!
Let's see who is going to fit in?

**Comment by JapanYoshi** [comment]
You think you're Prometheus.

Prometheus gave humans fire, something that can burn down cities and injure or kill people, but nonetheless has many legitimate uses, such as cooking, heating, and lighting the way in the dark or the fog. Prometheus made human life better.

This was what the Biro ball point pen was. It democratized writing and drawing to a wide demographic, making it available much more conveniently, at a much lower price. Literacy rates improved drastically once people had the power to write.

---

Now, imagine that Prometheus's fire can ONLY burn down buildings, statues, and books. Would Prometheus have been justified to spread this evil onto humans? Of course not. Prometheus could try to come up with ad-hoc rationalizations, like "Well maybe it can help demolish old buildings", but much better and less harmful methods already exist to demolish old buildings.

This is what this repository does. It creates nothing new except lies, fraud, and deception. You can rationalize the existence of this lying robot by imagining what a real artist could use it for, but those are just rationalizations with zero demand from any tangible person outside that hypothetical.

This AI is a solution looking for a problem. Nay, this AI is a menace looking for an excuse to exist.

**Comment by davizca** [comment]
Quick reminder this is for "issues". To give your opinion of how good or bad is the AI this is not the place.

**Comment by davizca** [comment]
Quick reminder that this is for ISSUES. To give your opinion about how good or bad is the AI this is not right place. You can go to discussions but mind that we are in a Github repo, lol.

**Comment by JapanYoshi** [comment]
> Quick reminder that this is for ISSUES.

The existence of this entire repo is the issue.

**Comment by davizca** [comment]
So your master plan is just downvote everyting not aligned with your vision and continue to spam messages till you get blocked or something from this repo? That's the master plan I guess. Anyways, well... good luck on fighting also the forked repos and copies too.

**Comment by EricUmbara** [comment]
> Really the assholes programmers want to disguise this as a way to support artists when it will simply be used to counterfeit art, they try to absolve themselves of all blame by saying that it is not their responsibility for how people use this shitty tool that was created specifically to counterfeit
> 
> I do blame you and I hope people do too

The evaluation appears to carry a subtle undertone of stress, reflecting a result-driven utilitarian approach. The purpose of engaging in any activity should be self-fulfillment rather than concern for the residual value extracted by society on a daily basis. Those who fail to grasp this concept may not be suited for art. If one truly loves and derives pleasure from art, concerns about whether an AI has 'violated' their utilitarian mindset may become less significant.

**Comment by Kotori05** [comment]
> Now, imagine that Prometheus's fire can ONLY burn down buildings, statues, and books. Would Prometheus have been justified to spread this evil onto humans? Of course not. Prometheus could try to come up with ad-hoc rationalizations, like "Well maybe it can help demolish old buildings", but much better and less harmful methods already exist to demolish old buildings.
> 
lmao, are you Biden?
You have lost even the basic logic. Good and evil are used to define subjective things, you try to use it to define fire?
Primitive people said the same thing before they learned how to use fire.

You should just go punching the fraudsters instead of harassing the researchers.

**Comment by tavyra** [comment]
> Really the assholes programmers want to disguise this as a way to support artists when it will simply be used to counterfeit art, they try to absolve themselves of all blame by saying that it is not their responsibility for how people use this shitty tool that was created specifically to counterfeit

l was an artist before a techbro so I feel inclined to point out the free market only creates things out of demand. Regardless of the point of this project, the reason this is a problem for you is you've created an isolationist group with rules for how money moves instead of working on integrating the tools and being more productive. Complain it's not fair, I agree. Nothing about capital is fair, but as an artist, this tool doesn't hurt me at all because I didn't invest any energy into fighting the tides of change.

**Comment by Shen-lon** [comment]
didnt know crying artists can create issues, But they still miss the point of the issues anyway, as expected from them


https://github.com/lllyasviel/Paints-UNDO/assets/172938297/41dd599b-4e78-4496-8eb9-4cbaa742f4c2

**Comment by barepixels** [comment]
> [Yosshi999](https://github.com/Yosshi999) 
> AI bros belike "lol I can generate*ARTS* by simply writing prompts" while tryin' hard to mimic the labor done by REAL ARTISTS doing REAL ARTS

I can tell you that prompts played a very small role in this
![workflow3](https://github.com/lllyasviel/Paints-UNDO/assets/92839033/95b4352e-f3e8-4d49-9807-b56bd9f366f5)

**Comment by Elvira626** [comment]
ghost, you shouldn't have even started this discussion. Not that I disagree with you. But these people know exactly what they're doing. They're massive trolls. But who cares? But at the end of the day, we're artists and they're not. 

This feature is going to be most useful to scammers and posers. We all know it. They can spew out their word salad lame explanations and arguments but it doesn't change a thing.

Dust off your easels, your sketchbook, your paintboxes and start painting the old school way, the way that Dan Dos Santos and Carla Ortiz do. With traditional oil or acrylics or your other media of choice. Stupid AI features like this can't fake that and never will.

**Comment by Amorano** [comment]
> ghost, you shouldn't have even started this discussion. Not that I disagree with you. But these \

Ghost isn't an account. Its the account that was deleted. You are responding to a troll that was removed because of the same bullshit you just posted.

Show us how we are all losers and go do a better job than the years as an artist and technical artist I have done. 

Prove all us tool makers and tool users wrong who have done nothing but help you your entire life.

Dont tell, show.

**Comment by Elvira626** [comment]
> Ghost isn't an account. Its the account that was deleted. You are responding to a troll that was removed because of the same bullshit you just posted.

Ah, I see. I'm a newbie.

> Dont tell, show.

I'm not here to convince you all of anything. You've already drunk your Kool-Aid. I was responding only to the person who started this thread. I was telling them why their protests were fruitless. I was telling them to not be fussed, because nobody can ever fake really being an artist and we all know it.

You all do whatever you're going to do. I said what I said. I'm saying it to other artists who stumble upon this discussion. 

Real artists who can actually paint need to channel people like Dan Dos Santos and Carla Ortiz and get back into oils and acrylics. AI will have a lot harder time faking "work in progress" time lapses of traditional painters because the traditional WIPs are not limited to a Photoshop screen capture or whatever. AI will have to fake a person at an easel, mixing paints, the movements of the artist's hands, the different types of easels, the whole thing. Good luck with that. It's harder to scam and lie and fake when there's a physical original piece of art.

**Comment by Amorano** [comment]
> Real artists who can actually paint need to channel people like Dan Dos Santos and Carla Ortiz and get back into oils and acrylics. AI will have a lot harder time faking "work in progress" time lapses of traditional painters because the traditional WIPs are not limited to a Photoshop screen capture or whatever. AI will have to fake a person at an easel, mixing paints, the movements of the artist's hands, the different types of easels, the whole thing. Good luck with that. It's harder to scam and lie and fake when there's a physical original piece of art.

correct and I 100% agree with this. Artists are artists -- THE MEDIUM THEY USE IS NOT.

Simple concept that a lot of "artists" cant seem to grasp.

**Comment by Elvira626** [comment]
>THE MEDIUM THEY USE IS NOT.

Unless the "medium" is a computer they commission to do the art _for_ them, lol.

**Comment by AndreiSva** [comment]
What qualifies as "art" differs widely based on personal beliefs. I think in most definitions it has a significant emotional aspect to it. 

Simply put, if someone perceives it as art, then it is art.

**Comment by lllyasviel** [comment]
Hi all, as an action of [GitHub ToS]( https://docs.github.com/en/site-policy/acceptable-use-policies/github-bullying-and-harassment) we must lock this thread. 

For future comments please follow the instructions [here](https://github.com/lllyasviel/Paints-UNDO/issues/41).
