### ISSUE TITLE
Removed from hugginface?

### ISSUE THREAD

**Issue by flabble** [lllyasviel/Paints-UNDO#97]
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/Ubuntu/miniconda3/envs/paints_undo/lib/python3.10/site-packages/huggingface_hub/__init__.py)

**Comment by cherifyd** [comment]
you can fix it with :  pip install huggingface_hub==0.24.7

source:
https://github.com/FunAudioLLM/CosyVoice/issues/516

**Comment by ReloadProcz** [comment]
Just DOWNGRADE your huggingface-hub version is OK.
e.g. My huggingface-hub version is 0.24.0. That works.(huggingface-hub<=0.25.0, Maybe?)
